version: "3.2"

networks:
   frontend:
   backend:

services:
   webmvc:
      build:
         context: .\src\Web\webmvc
         dockerfile: Dockerfile
      container_name: webfront
      environment:
         - ASPNETCORE_ENVIRONMENT=Development
         - CatalogUrl=http://catalog
         - IdentityUrl=http://10.0.75.1:5000
      ports:
         - "5200:80"
      networks:
         - frontend
      depends_on:
         - catalog
         - tokenserver

   catalog:
      build:
         context: .\src\Services\ProductCatalogApi
         dockerfile: Dockerfile
      image: shoes/catalog
      container_name: catalogapi
      environment:
         - DatabaseServer=mssqlserver
         - DatabaseName=CatalogDb
         - DatabaseUser=sa
         - DatabaseUserPassword=ProductApi(!)
      ports:
         - "5100:80"
      networks:
         - backend
         - frontend
      depends_on:
         - mssqlserver
   
   tokenserver:
      build:
         context: .\src\Services\TokenServiceApi
         dockerfile: Dockerfile
      environment:
         - ASPNETCORE_ENVIRONMENT=Development
         - MvcClient=http://localhost:5200
         - DatabaseServer=mssqlserver
         - DatabaseName=TokenServerDb
         - DatabaseUser=sa
         - DatabaseUserPassword=ProductApi(!)
      container_name: tokenserviceapi
      ports:
         - "5000:80"
      networks:
         - backend
         - frontend
      depends_on:
         - mssqlserver
         - catalog

   mssqlserver:
      image: "microsoft/mssql-server-linux:latest"
      container_name: mssqlcontainer
      environment:
         - ACCEPT_EULA=Y
         - SA_PASSWORD=ProductApi(!)
      ports:
         - "1445:1433"
      networks:
         - backend      